/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-tint": "#515f78",
        "on-surface-variant": "#44474d",
        "on-tertiary-container": "#b47700",
        "primary-fixed-dim": "#b9c7e4",
        "on-tertiary-fixed": "#291800",
        "secondary": "#00677f",
        "on-secondary": "#ffffff",
        "outline": "#75777e",
        "on-error-container": "#93000a",
        "surface-container-highest": "#e0e3e6",
        "surface-container-low": "#f1f4f7",
        "surface-container": "#ebeef1",
        "tertiary-fixed": "#ffddb3",
        "secondary-fixed": "#b6ebff",
        "tertiary": "#000000",
        "primary": "#000000",
        "on-secondary-container": "#00566a",
        "inverse-surface": "#2d3133",
        "primary-fixed": "#d6e3ff",
        "on-background": "#181c1e",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#291800",
        "on-primary-container": "#76849f",
        "on-primary": "#ffffff",
        "surface-bright": "#f7fafd",
        "surface": "#f7fafd",
        "on-secondary-fixed": "#001f28",
        "primary-container": "#0d1c32",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e5e8eb",
        "secondary-fixed-dim": "#47d6ff",
        "tertiary-fixed-dim": "#ffb950",
        "secondary-container": "#00d2ff",
        "surface-dim": "#d7dadd",
        "on-primary-fixed": "#0d1c32",
        "inverse-primary": "#b9c7e4",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#39475f",
        "on-secondary-fixed-variant": "#004e60",
        "inverse-on-surface": "#eef1f4",
        "on-tertiary-fixed-variant": "#624000",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "outline-variant": "#c5c6cd",
        "on-surface": "#181c1e",
        "surface-variant": "#e0e3e6",
        "background": "#f7fafd"
      },
      fontFamily: {
        "headline": ["Manrope", "Pretendard"],
        "body": ["Pretendard"],
        "label": ["Pretendard"]
      },
      borderRadius: {
        "brand": "14px",
      },
    },
  },
  plugins: [],
}
